### ISSUE TITLE
hatter.hu: alap színpaletta nem helyes

### ISSUE THREAD

**Issue by tdombos** [tdombos/odoo#113]
A default színpalettának illeszkednie kellene a Háttér színeihez, ezt le lehet kézzel cserélni, és csak 1x kell beállítani, de jobb lenne a témába tenni.

**Comment by mdombos** [comment]
A designbol nekem nem derül ki, hogy milyen színeket kellene beállítani.

**Comment by tdombos** [comment]
o-color-1 (Primary): türkiz (gombok, felsőmenü betűinek színe)
o-color-2 (Secondary): középszürke (megamenu v2 körök színe)
o-color-3 (Extra): világos szürke (breadcrumb, kiadvány doboz hátterének színe)
o-color-4 (Whitish): fehér (oldal háttere)
o-color-5 (Blackish): fekete (sima szöveg színe)
