### ISSUE TITLE
[BI] fiókom menüpont formázása

### ISSUE THREAD

**Issue by tdombos** [tdombos/odoo#65]
Belépés után fiókom / kilépés menüpont nincs megformázva.![IMG_20220326_101417.jpg](https://user-images.githubusercontent.com/352280/160232993-669fb7a0-51e5-4da0-8f9b-876b5ac4d854.jpg)

**Comment by mdombos** [comment]
Úgy látom ez is megjavult így hogy visszaváltozzam a navbar típusát

**Comment by tdombos** [comment]
Igen.
